// <auto-generated />
namespace CodeFirstExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changed_FirstNam_To_FirstName_InPeopleTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_FirstNam_To_FirstName_InPeopleTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806231419358_Changed_FirstNam_To_FirstName_InPeopleTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
